after_script:
  - echo "Clean up activity can be done here !."

stages:
  - build
  - test
  - build_image

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

build_image:
  stage: build_image
  image: docker:latest
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image /Dockerfile


