stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  HEROKU_APP_NAME: "codenemy-backend"
  HEROKU_PRODUCTION_KEY: "daabb8a1-d96f-4d7e-94b5-1ffc930e0547"

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

heroku_deploy:
 stage: deploy
 only:
  - main
 image: ruby:latest
 script:
  - gem install dpl && gem install faraday -v 1.8.0
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY


